### ISSUE TITLE
Wheely's exist in the arcade machine across the map.

### ISSUE THREAD

**Issue by pilotbland** [FortunaSS13/Fortuna#120]
## Round ID:
148 but is obviously in any round.

## Testmerges:
No.

## Reproduction:
Win in this gamemode's game

https://i.gyazo.com/d54670d5090ae09c34a2bd95e09beece.png
eventually get Wheely Shoes

play the game long enough, get wheely shoes which are SUPER FUCKING FAST.

**Comment by buffyuwu** [comment]
this will be fixed when #199 gets merged

**Comment by buffyuwu** [comment]
issue can be marked as resolved from #199
