### ISSUE TITLE
Revertion of the Chaplain "Nerf"

### ISSUE THREAD

**Issue by Wotzizname** [FortunaSS13/Fortuna#181]
So,not so recently the Chaplain has been moved out of Oasis into the chapel to save space!
Thing is,some other changes have been made aswell sadly.The Chaplain's Children of Atom loadout was ripped and the null rod's ability to change forms also was!
All we got was just a nerfed chaplain with a possibly fun role taken from it.
The humble request of this request is to revert Chaplain back to before the removal of the null rod's ability to change and the Children of Atom loadout to be readded.

**Comment by zuliouse** [comment]
Children of Atom is Fo3/Fo4 lore, they have no reason to be in Yuma, and they are not canon for our server, which is why I removed the loadout. Its removal was not a nerf, it was for lore consistency.
