### ISSUE TITLE
Sherrif peacekeeper

### ISSUE THREAD

**Issue by VEN0M5** [FortunaSS13/Fortuna#184]
## Reproduction:Sherrif's peacekeeper does not reset the fire delay after switching back from fan the hammer... Although a fire delay of 10 is pain. Suggest to lower the fire delay while fixing this

![Screenshot_20210921-122257~2](https://user-images.githubusercontent.com/15703585/134111337-b405fe0d-7180-4d82-9be2-7e229a12ebcb.png)

**Comment by ThyBaron** [comment]
Fixed!
