### ISSUE TITLE
Nuka Victory text is much bigger than the average drink examine text

### ISSUE THREAD

**Issue by BadAtThisGame302** [FortunaSS13/Fortuna#22]
## Reproduction:
Examine a Nuka Victory and see

**Comment by pilotbland** [comment]
Comparison (provided by @BadAtThisGame302 who made the bug report)

https://cdn.discordapp.com/attachments/875768006423248918/877561912269893642/unknown.png
normal drink

https://cdn.discordapp.com/attachments/875768006423248918/877561764856856586/unknown.png
nuka victory

**Comment by Cinnamon-BonBon** [comment]
Intended

It's Nuka **Victory** not Nuka Failure.
