### ISSUE TITLE
Paraplegic Quirk / Trait spawns you with a floating wheelchair.

### ISSUE THREAD

**Issue by pilotbland** [FortunaSS13/Fortuna#27]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
Use the quirk/trait 'paraplegic' and you get a floating techy spacer-tech wheelchair with green laser exhausts, etc.

https://i.gyazo.com/da1cc1fc1b192772394906ca1ee78313.png

This is not... uh, 'F13'. I think there's a regular wheelchair in the code.

**Comment by myass21** [comment]
Do you know where the file location is? I'll try to fix it.

**Comment by Mrfilms** [comment]
It's an issue that's bothered me since I first noticed it in the Fortune days, I replaced the rocket sprite with the traditional wheelchair sprite [here](https://github.com/FortunaSS13/Fortuna/pull/31).
