### ISSUE TITLE
zip gun self-reports itself

### ISSUE THREAD

**Issue by pilotbland** [FortunaSS13/Fortuna#36]
https://i.gyazo.com/3544e13ccd9e25c5fa4ca2a91612c4a5.png

There's a 9mm zip gun that says 'report this'. I don't know if this is a troll or not or (why) it would need a bug report.

/obj/item/gun/ballistic/automatic/hobo/zipgun

**Comment by Looreydev** [comment]
Probably just someone that was too lazy to change a description.

**Comment by buffyuwu** [comment]
can be closed
