### ISSUE TITLE
Bar in Oasis needs it's Booze-o-mat moved.

### ISSUE THREAD

**Issue by pilotbland** [FortunaSS13/Fortuna#65]
The currently PRed map by @Mannybrado (mapping genius and unparalleled concisest mapper NA) used a booze-o-mat as one of the machines embedded to the wall. It blocks the tile leading to the back door, leading the bar inaccessible until an admin moves it themselves.

So for example, and this is not where the machine is located, if it's placed somewhere, the tile adjacent to it's left, one tile up--is inaccessible.

https://cdn.discordapp.com/attachments/875768006423248918/881288178064031764/blocked.PNG

**Comment by pilotbland** [comment]
https://i.gyazo.com/5d29f983a1b299a6ff7fa8ba063467fe.png

This is where the booze-o-mat is by default. It blocks the space closest to the barman there, blocking the tile right infront of the door.

**Comment by Mannybrado** [comment]
#64 this pr fixes this issue, close it!!!!!!!!!!!!!!!1
