### ISSUE TITLE
Combat Mode disables Stamina Regen

### ISSUE THREAD

**Issue by zuliouse** [FortunaSS13/Fortuna#72]
Combat Mode disabling stamina regen makes activating it a direct disadvantage, which in turn discourages players from activating their Combat Indicator during combat. This is obviously not favorable, as Combat Mode is _required_ for combat by our rules. It would be favorable if Combat Mode was purely a cosmetic thing, with no direct changes or disadvantages beyond a simple notification.

**Comment by hecksadecimal** [comment]
I'll tackle this.

**Comment by ThyBaron** [comment]
Fixed!
