### ISSUE TITLE
Remove the bluespace plant trait.

### ISSUE THREAD

**Issue by zuliouse** [FortunaSS13/Fortuna#91]
Teleporting plants is not good for a multitude of obvious reasons, and this trait is still accessible if plants are mutated. Removal would be appreciated.

**Comment by mishulinya** [comment]
Will speedrun it, give me some minutes.

**Comment by mishulinya** [comment]
Ok done, just waiting for the quirk fix PR to be accepted and i'll make the PR for removing the trait.

**Comment by Looreydev** [comment]
> Ok done, just waiting for the quirk fix PR to be accepted and i'll make the PR for removing the trait.

Daily reminder that you can have multiple PR's open.

**Comment by AdamElTablawy** [comment]
close dis
